### ISSUE TITLE
Issue with Page source box overlapping sidebar

### ISSUE THREAD

**Issue by hwahyeon** [LispCookbook/cl-cookbook#558]
![screenshot](https://github.com/user-attachments/assets/b6ca1a29-e791-41e1-a8d0-7f40f5170740)

```css
#toc-btn{
     z-index: 2; // above the toc-container
   ...
}
#toc-container{
    z-index:1; // above the "page source" bar
   ...
}
```

It seems that `z-index: 1` is set on `#toc-container`, but it may not be working as expected. This could be due to the parent element, `#logo-container`, creating a stacking context, which limits the effect of the child element's `z-index` within the parent. I believe adding `z-index: 1` to the parent(`#logo-container`) could resolve this issue.

```css
#logo-container{
    height:90px;
    width:23%;
    margin-left:1%;
    margin-right:1%;
    position:fixed;
    z-index:1; // add z-index
}
```

I'm open to any other suggestions.
Thanks!
